// generated with @7nohe/openapi-react-query-codegen@2.0.0 

import { type Options } from "@hey-api/client-fetch";
import { useMutation, UseMutationOptions, useQuery, UseQueryOptions } from "@tanstack/react-query";
import { healthControllerCheck, jobsControllerCancel, jobsControllerCreate, jobsControllerGet, jobsControllerList } from "../requests/services.gen";
import { HealthControllerCheckError, JobsControllerCancelData, JobsControllerCancelError, JobsControllerCreateData, JobsControllerCreateError, JobsControllerGetData, JobsControllerGetError, JobsControllerListError } from "../requests/types.gen";
import * as Common from "./common";
export const useJobsControllerList = <TData = Common.JobsControllerListDefaultResponse, TError = JobsControllerListError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseJobsControllerListKeyFn(clientOptions, queryKey), queryFn: () => jobsControllerList({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useJobsControllerGet = <TData = Common.JobsControllerGetDefaultResponse, TError = JobsControllerGetError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<JobsControllerGetData, true>, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseJobsControllerGetKeyFn(clientOptions, queryKey), queryFn: () => jobsControllerGet({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useHealthControllerCheck = <TData = Common.HealthControllerCheckDefaultResponse, TError = HealthControllerCheckError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useQuery<TData, TError>({ queryKey: Common.UseHealthControllerCheckKeyFn(clientOptions, queryKey), queryFn: () => healthControllerCheck({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useJobsControllerCreate = <TData = Common.JobsControllerCreateMutationResult, TError = JobsControllerCreateError, TQueryKey extends Array<unknown> = unknown[], TContext = unknown>(mutationKey?: TQueryKey, options?: Omit<UseMutationOptions<TData, TError, Options<JobsControllerCreateData, true>, TContext>, "mutationKey" | "mutationFn">) => useMutation<TData, TError, Options<JobsControllerCreateData, true>, TContext>({ mutationKey: Common.UseJobsControllerCreateKeyFn(mutationKey), mutationFn: clientOptions => jobsControllerCreate(clientOptions) as unknown as Promise<TData>, ...options });
export const useJobsControllerCancel = <TData = Common.JobsControllerCancelMutationResult, TError = JobsControllerCancelError, TQueryKey extends Array<unknown> = unknown[], TContext = unknown>(mutationKey?: TQueryKey, options?: Omit<UseMutationOptions<TData, TError, Options<JobsControllerCancelData, true>, TContext>, "mutationKey" | "mutationFn">) => useMutation<TData, TError, Options<JobsControllerCancelData, true>, TContext>({ mutationKey: Common.UseJobsControllerCancelKeyFn(mutationKey), mutationFn: clientOptions => jobsControllerCancel(clientOptions) as unknown as Promise<TData>, ...options });
