// generated with @7nohe/openapi-react-query-codegen@2.0.0 

import { type Options } from "@hey-api/client-fetch";
import { useSuspenseQuery, UseSuspenseQueryOptions } from "@tanstack/react-query";
import { healthControllerCheck, jobsControllerGet, jobsControllerList } from "../requests/services.gen";
import { HealthControllerCheckError, JobsControllerGetData, JobsControllerGetError, JobsControllerListError } from "../requests/types.gen";
import * as Common from "./common";
export const useJobsControllerListSuspense = <TData = NonNullable<Common.JobsControllerListDefaultResponse>, TError = JobsControllerListError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseSuspenseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseJobsControllerListKeyFn(clientOptions, queryKey), queryFn: () => jobsControllerList({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useJobsControllerGetSuspense = <TData = NonNullable<Common.JobsControllerGetDefaultResponse>, TError = JobsControllerGetError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<JobsControllerGetData, true>, queryKey?: TQueryKey, options?: Omit<UseSuspenseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseJobsControllerGetKeyFn(clientOptions, queryKey), queryFn: () => jobsControllerGet({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
export const useHealthControllerCheckSuspense = <TData = NonNullable<Common.HealthControllerCheckDefaultResponse>, TError = HealthControllerCheckError, TQueryKey extends Array<unknown> = unknown[]>(clientOptions: Options<unknown, true> = {}, queryKey?: TQueryKey, options?: Omit<UseSuspenseQueryOptions<TData, TError>, "queryKey" | "queryFn">) => useSuspenseQuery<TData, TError>({ queryKey: Common.UseHealthControllerCheckKeyFn(clientOptions, queryKey), queryFn: () => healthControllerCheck({ ...clientOptions }).then(response => response.data as TData) as TData, ...options });
