// This file is auto-generated by @hey-api/openapi-ts

export const CreateJobDtoSchema = {
    type: 'object',
    properties: {
        urls: {
            description: 'List of http/https URLs to check (deduplicated server-side).',
            example: ['https://example.com', 'https://nestjs.com'],
            type: 'array',
            items: {
                type: 'string'
            }
        }
    },
    required: ['urls']
} as const;

export const CreateJobResponseDtoSchema = {
    type: 'object',
    properties: {
        jobId: {
            type: 'string',
            description: 'Unique identifier of the newly created job.',
            example: 'b3f1c2e4-5a6b-7c8d-9e0f-1a2b3c4d5e6f'
        }
    },
    required: ['jobId']
} as const;

export const JobStatusSchema = {
    type: 'string',
    enum: ['pending', 'in_progress', 'completed', 'cancelled', 'failed']
} as const;

export const JobSummaryStatsDtoSchema = {
    type: 'object',
    properties: {
        success: {
            type: 'number',
            example: 3
        },
        error: {
            type: 'number',
            example: 1
        }
    },
    required: ['success', 'error']
} as const;

export const JobSummaryDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: 'b3f1c2e4-5a6b-7c8d-9e0f-1a2b3c4d5e6f'
        },
        createdAt: {
            type: 'string',
            example: '2026-06-23T10:00:00.000Z'
        },
        status: {
            '$ref': '#/components/schemas/JobStatus'
        },
        urlCount: {
            type: 'number',
            example: 4
        },
        stats: {
            '$ref': '#/components/schemas/JobSummaryStatsDto'
        }
    },
    required: ['id', 'createdAt', 'status', 'urlCount', 'stats']
} as const;

export const JobDetailStatsDtoSchema = {
    type: 'object',
    properties: {
        success: {
            type: 'number',
            example: 3
        },
        error: {
            type: 'number',
            example: 1
        },
        pending: {
            type: 'number',
            example: 0
        },
        inProgress: {
            type: 'number',
            example: 0
        },
        cancelled: {
            type: 'number',
            example: 0
        }
    },
    required: ['success', 'error', 'pending', 'inProgress', 'cancelled']
} as const;

export const UrlStatusSchema = {
    type: 'string',
    enum: ['pending', 'in_progress', 'success', 'error', 'cancelled']
} as const;

export const UrlResultDtoSchema = {
    type: 'object',
    properties: {
        url: {
            type: 'string',
            example: 'https://example.com'
        },
        status: {
            '$ref': '#/components/schemas/UrlStatus'
        },
        httpStatus: {
            type: 'number',
            nullable: true,
            example: 200,
            description: 'HTTP status code returned by the HEAD request, if any.'
        },
        error: {
            type: 'string',
            nullable: true,
            example: null,
            description: 'Error detail (e.g. "timeout", "ENOTFOUND", "HTTP 404").'
        },
        startedAt: {
            type: 'string',
            nullable: true,
            example: null
        },
        finishedAt: {
            type: 'string',
            nullable: true,
            example: null
        },
        durationMs: {
            type: 'number',
            nullable: true,
            example: null
        }
    },
    required: ['url', 'status', 'httpStatus', 'error', 'startedAt', 'finishedAt', 'durationMs']
} as const;

export const JobDetailDtoSchema = {
    type: 'object',
    properties: {
        id: {
            type: 'string',
            example: 'b3f1c2e4-5a6b-7c8d-9e0f-1a2b3c4d5e6f'
        },
        createdAt: {
            type: 'string',
            example: '2026-06-23T10:00:00.000Z'
        },
        status: {
            '$ref': '#/components/schemas/JobStatus'
        },
        startedAt: {
            type: 'string',
            nullable: true
        },
        finishedAt: {
            type: 'string',
            nullable: true
        },
        processed: {
            type: 'number',
            example: 4,
            description: 'total - pending - inProgress'
        },
        stats: {
            '$ref': '#/components/schemas/JobDetailStatsDto'
        },
        urls: {
            type: 'array',
            items: {
                '$ref': '#/components/schemas/UrlResultDto'
            }
        }
    },
    required: ['id', 'createdAt', 'status', 'startedAt', 'finishedAt', 'processed', 'stats', 'urls']
} as const;