// This file is auto-generated by @hey-api/openapi-ts

import { createClient, createConfig, type Options } from '@hey-api/client-fetch';
import type { JobsControllerCreateData, JobsControllerCreateError, JobsControllerCreateResponse, JobsControllerListError, JobsControllerListResponse, JobsControllerGetData, JobsControllerGetError, JobsControllerGetResponse, JobsControllerCancelData, JobsControllerCancelError, JobsControllerCancelResponse, HealthControllerCheckError, HealthControllerCheckResponse } from './types.gen';

export const client = createClient(createConfig());

/**
 * Create a URL-checking job (processes async).
 */
export const jobsControllerCreate = <ThrowOnError extends boolean = false>(options: Options<JobsControllerCreateData, ThrowOnError>) => { return (options?.client ?? client).post<JobsControllerCreateResponse, JobsControllerCreateError, ThrowOnError>({
    ...options,
    url: '/api/jobs'
}); };

/**
 * List jobs (newest first).
 */
export const jobsControllerList = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<JobsControllerListResponse, JobsControllerListError, ThrowOnError>({
    ...options,
    url: '/api/jobs'
}); };

/**
 * Get full job detail.
 */
export const jobsControllerGet = <ThrowOnError extends boolean = false>(options: Options<JobsControllerGetData, ThrowOnError>) => { return (options?.client ?? client).get<JobsControllerGetResponse, JobsControllerGetError, ThrowOnError>({
    ...options,
    url: '/api/jobs/{id}'
}); };

/**
 * Cancel a job (idempotent). Returns full detail.
 */
export const jobsControllerCancel = <ThrowOnError extends boolean = false>(options: Options<JobsControllerCancelData, ThrowOnError>) => { return (options?.client ?? client).delete<JobsControllerCancelResponse, JobsControllerCancelError, ThrowOnError>({
    ...options,
    url: '/api/jobs/{id}'
}); };

export const healthControllerCheck = <ThrowOnError extends boolean = false>(options?: Options<unknown, ThrowOnError>) => { return (options?.client ?? client).get<HealthControllerCheckResponse, HealthControllerCheckError, ThrowOnError>({
    ...options,
    url: '/api/health'
}); };