// This file is auto-generated by @hey-api/openapi-ts

export type CreateJobDto = {
    /**
     * List of http/https URLs to check (deduplicated server-side).
     */
    urls: Array<(string)>;
};

export type CreateJobResponseDto = {
    /**
     * Unique identifier of the newly created job.
     */
    jobId: string;
};

export type JobStatus = 'pending' | 'in_progress' | 'completed' | 'cancelled' | 'failed';

export type JobSummaryStatsDto = {
    success: number;
    error: number;
};

export type JobSummaryDto = {
    id: string;
    createdAt: string;
    status: JobStatus;
    urlCount: number;
    stats: JobSummaryStatsDto;
};

export type JobDetailStatsDto = {
    success: number;
    error: number;
    pending: number;
    inProgress: number;
    cancelled: number;
};

export type UrlStatus = 'pending' | 'in_progress' | 'success' | 'error' | 'cancelled';

export type UrlResultDto = {
    url: string;
    status: UrlStatus;
    /**
     * HTTP status code returned by the HEAD request, if any.
     */
    httpStatus: (number) | null;
    /**
     * Error detail (e.g. "timeout", "ENOTFOUND", "HTTP 404").
     */
    error: (string) | null;
    startedAt: (string) | null;
    finishedAt: (string) | null;
    durationMs: (number) | null;
};

export type JobDetailDto = {
    id: string;
    createdAt: string;
    status: JobStatus;
    startedAt: (string) | null;
    finishedAt: (string) | null;
    /**
     * total - pending - inProgress
     */
    processed: number;
    stats: JobDetailStatsDto;
    urls: Array<UrlResultDto>;
};

export type JobsControllerCreateData = {
    body: CreateJobDto;
};

export type JobsControllerCreateResponse = (CreateJobResponseDto);

export type JobsControllerCreateError = unknown;

export type JobsControllerListResponse = (Array<JobSummaryDto>);

export type JobsControllerListError = unknown;

export type JobsControllerGetData = {
    path: {
        id: string;
    };
};

export type JobsControllerGetResponse = (JobDetailDto);

export type JobsControllerGetError = (unknown);

export type JobsControllerCancelData = {
    path: {
        id: string;
    };
};

export type JobsControllerCancelResponse = (JobDetailDto);

export type JobsControllerCancelError = (unknown);

export type HealthControllerCheckResponse = (unknown);

export type HealthControllerCheckError = unknown;